spring:
  application:
    name: usian-item-web
server:
  port: 8091

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
fdfs:
  so-timeout: 1501 #超时时间
  connect-timeout: 601 #连接超时时间
  thumb-image:
    width: 60
    height: 60
  tracker-list:
    - 192.168.2.129:22122