spring:
  application:
    name: usian-search-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/usian?characterEncoding=UTF-8
    username: root
    password: 123
    type: com.alibaba.druid.pool.DruidDataSource
  data:
    elasticsearch:
      cluster-nodes: 192.168.2.132:9200,192.168.2.133:9200
server:
  port: 8095
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/

#索引名称
ES_INDEX_NAME: usian
#类型名称
ES_TYPE_NAME: item