spring:
  application:
    name: usian-order-web
server:
  port: 8103
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/

#设置feign超时时间
ribbon:
  ConnectTimeout: 6000
  ReadTimeout: 6000